name: Prueba
on: workflow_dispatch
env: 
  DIA_DE_SEMANA: lunes
jobs:
  saludo-variables:
    runs_on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO $NOMBRE, hoy es $DIA_DE_SEMANA"
        env:
          NOMBRE: Helqui
