name: Secretos
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo con variables
        run: echo "${{ vars.NOMBRE }} eres el mejor, el día SDIA_DE_SEMANA !"
